/**
 * IOC to ISO-3166 alpha-2, for the live feed only.
 *
 * The archive's `normalizeCountryCode` in @/lib/utils/flags maps ISO-3166
 * alpha-3, because that is what SportRadar sent. LiveTennisAPI sends a
 * different vocabulary and says so outright: "IOC-style lowercase 3-letter
 * codes". The two disagree on exactly the countries tennis cares about -
 * ger/deu, ned/nld, sui/che, cro/hrv, gre/grc, por/prt, chi/chl, den/dnk -
 * so reusing the archive's map would have silently dropped the flags of
 * Germany, the Netherlands and Switzerland.
 */
const IOC_TO_ISO2: Record<string, string> = {
  alg: "DZ",
  and: "AD",
  arg: "AR",
  arm: "AM",
  aru: "AW",
  aus: "AU",
  aut: "AT",
  aze: "AZ",
  bah: "BS",
  bar: "BB",
  bdi: "BI",
  bel: "BE",
  ben: "BJ",
  ber: "BM",
  bih: "BA",
  blr: "BY",
  bol: "BO",
  bot: "BW",
  bra: "BR",
  brn: "BH",
  bul: "BG",
  cam: "KH",
  can: "CA",
  chi: "CL",
  chn: "CN",
  civ: "CI",
  cmr: "CM",
  col: "CO",
  crc: "CR",
  cro: "HR",
  cub: "CU",
  cyp: "CY",
  cze: "CZ",
  den: "DK",
  dom: "DO",
  ecu: "EC",
  egy: "EG",
  esa: "SV",
  esp: "ES",
  est: "EE",
  eth: "ET",
  fin: "FI",
  fra: "FR",
  gab: "GA",
  gbr: "GB",
  geo: "GE",
  ger: "DE",
  gha: "GH",
  gre: "GR",
  gua: "GT",
  hai: "HT",
  hkg: "HK",
  hon: "HN",
  hun: "HU",
  ina: "ID",
  ind: "IN",
  iri: "IR",
  irl: "IE",
  irq: "IQ",
  isl: "IS",
  isr: "IL",
  ita: "IT",
  jam: "JM",
  jor: "JO",
  jpn: "JP",
  kaz: "KZ",
  ken: "KE",
  kor: "KR",
  kos: "XK",
  ksa: "SA",
  kuw: "KW",
  lat: "LV",
  lba: "LY",
  lbn: "LB",
  lie: "LI",
  ltu: "LT",
  lux: "LU",
  mad: "MG",
  mar: "MA",
  mas: "MY",
  mda: "MD",
  mex: "MX",
  mgl: "MN",
  mkd: "MK",
  mlt: "MT",
  mne: "ME",
  mon: "MC",
  ned: "NL",
  ngr: "NG",
  nor: "NO",
  nzl: "NZ",
  pak: "PK",
  pan: "PA",
  par: "PY",
  per: "PE",
  phi: "PH",
  pol: "PL",
  por: "PT",
  pur: "PR",
  qat: "QA",
  rou: "RO",
  rsa: "ZA",
  rus: "RU",
  srb: "RS",
  sgp: "SG",
  slo: "SI",
  sui: "CH",
  svk: "SK",
  swe: "SE",
  syr: "SY",
  tha: "TH",
  tpe: "TW",
  tto: "TT",
  tun: "TN",
  tur: "TR",
  uae: "AE",
  ukr: "UA",
  uru: "UY",
  usa: "US",
  uzb: "UZ",
  ven: "VE",
  vie: "VN",
  zim: "ZW",
};

/**
 * Returns the ISO-3166 alpha-2 code a flag asset is named after, or "UN" -
 * which has its own asset - when the code is unknown, absent, or a neutral
 * designation. Never returns the input unchanged: an unmapped 3-letter code
 * would render as a broken image rather than an honest placeholder.
 */
export function iocToIso2(code: string | null | undefined): string {
  if (!code) return "UN";
  return IOC_TO_ISO2[code.toLowerCase()] ?? "UN";
}
